/* Generated By:JavaCC: Do not edit this line. BelaConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BelaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int APAR = 7;
  /** RegularExpression Id. */
  int FPAR = 8;
  /** RegularExpression Id. */
  int ACHAVES = 9;
  /** RegularExpression Id. */
  int FCHAVES = 10;
  /** RegularExpression Id. */
  int TFLOAT = 11;
  /** RegularExpression Id. */
  int TBOOL = 12;
  /** RegularExpression Id. */
  int TVOID = 13;
  /** RegularExpression Id. */
  int ATRIBUICAO = 14;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int READINPUT = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int PRINTLN = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int OPADI = 24;
  /** RegularExpression Id. */
  int OPSUB = 25;
  /** RegularExpression Id. */
  int OPMULT = 26;
  /** RegularExpression Id. */
  int OPDIV = 27;
  /** RegularExpression Id. */
  int OPAND = 28;
  /** RegularExpression Id. */
  int OPOR = 29;
  /** RegularExpression Id. */
  int OPMENOR = 30;
  /** RegularExpression Id. */
  int OPMAIOR = 31;
  /** RegularExpression Id. */
  int OPIGUAL = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int FUNC = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"var\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"float\"",
    "\"bool\"",
    "\"void\"",
    "\"=\"",
    "\";\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"readInput\"",
    "\"return\"",
    "\"printLn\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"fun\"",
    "<NUM>",
    "<ID>",
  };

}
